// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Head from "next/head";
// import NavBar from "@/components/NavBar";
// import Footer from "@/components/Footer";
// import { Toaster } from "react-hot-toast";

// import { StateProvider } from '@/context/StateContext'
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <Head><h1>My E-commerce Site</h1></Head>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <StateProvider>
//           <Toaster />
//           <div className="container">
//             <NavBar />
//             <main className="main-container">{children}</main>
//             <Footer />
//           </div>
//           <div className="layout">
//             <header>
//               <NavBar />
//             </header>
//             <main className="main-container">{children}</main>
//             <footer>
//               <Footer />
//             </footer>
//           </div>
//         </StateProvider>

//       </body>
//     </html >
//   );
// }
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import { StateProvider } from '@/context/StateContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My E-commerce Site",
  description: "Best products online",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StateProvider>
          <Toaster />
          <div className="layout">
            <header>
              <NavBar />
            </header>
            <main className="main-container">{children}</main>
            <footer>
              <Footer />
            </footer>
          </div>
        </StateProvider>
      </body>
    </html>
  );
}
